name: auto_langx
description: Automatic translation package for Flutter apps using Google Cloud Translation API. Translate text dynamically at runtime without .arb files.
version: 1.0.0
homepage: https://github.com/Ali02-dev/auto_langx
repository: https://github.com/Ali02-dev/auto_langx
issue_tracker: https://github.com/Ali02-dev/auto_langx/issues
publish_to: https://pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

# Metadata (optional but professional)
# This helps pub.dev show your author info properly.
contact:
  name: Ali Ijaz
  email: aliijaz9656@gmail.com
